body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting the post, please make sure you have completed the following
      options:
        - label: I have read all the documentation
          required: true
        - label: I have searched the existing discussions/issues
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the question
      description: A clear and concise description of what the question is
      placeholder: Tell us what you want to know
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Add any other context about the problem here.  You can attach screenshots by clicking
        this area to highlight it and then drag the files in.
