name: 🐞 Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting the issue, please make sure you have completed the following
      options:
        - label: I've checked the existing Issue list, no duplicate issue
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Minimal reproducer
      description: A [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) is required, otherwise the issue might be closed without further notice.
      placeholder: |
        Please include as much information as possible that can help to reproduce and understand the issue.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Add any other context about the problem here.  You can attach screenshots by clicking
        this area to highlight it and then drag the files in.
