blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/zooeywm/kudi/discussions/new?category=q-a
    about: When you have questions that are not bug reports or feature requests
